name: Build & publish docker images
on:
  workflow_dispatch:
  push:
    branches: ["dev"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./packages/api
            image: ghcr.io/CameronBrooks11/freeboard-api
            name: api
          - context: ./packages/oauth
            image: ghcr.io/CameronBrooks11/freeboard-oauth
            name: oauth
          - context: ./packages/proxy
            image: ghcr.io/CameronBrooks11/freeboard-proxy
            name: proxy
          - context: ./packages/ui
            image: ghcr.io/CameronBrooks11/freeboard-ui
            name: ui

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if package has changed
        id: changes
        run: |
          echo "Checking for changes in ${{ matrix.context }}"
          git fetch origin dev
          CHANGED=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" -- "${{ matrix.context }}")
          if [ -z "$CHANGED" ]; then
            echo "No changes in ${{ matrix.context }}"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in ${{ matrix.context }}"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker
        if: steps.changes.outputs.changed == 'true'
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to the Container registry
        if: steps.changes.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.changes.outputs.changed == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata (tags, labels) for Docker
        if: steps.changes.outputs.changed == 'true'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        if: steps.changes.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Skipping build (no changes)
        if: steps.changes.outputs.changed == 'false'
        run: echo "No changes detected in ${{ matrix.name }} â€” skipping build."
